DROP DATABASE IF EXISTS project_MA_Twente;
CREATE DATABASE project_MA_Twente;
USE project_MA_Twente;

DROP TABLE IF EXISTS configuraties;
CREATE TABLE configuraties(
    cid INT AUTO_INCREMENT,
    besturingssysteem VARCHAR(20),
    type VARCHAR(20),
    model VARCHAR(20),
    proccessor VARCHAR(20),
    werkgeheugen VARCHAR(20),
    videokaart VARCHAR(20),
    harddrive VARCHAR(20),
    psu VARCHAR(20),
    bouwjaar DATE,
    licenties VARCHAR(20),
    PRIMARY KEY (cid)
);

INSERT INTO configuraties(cid, besturingssysteem, type, model, proccessor, werkgeheugen, Videokaart, Harddrive, psu, bouwjaar, licenties)
VALUES
(162,"Windows 10 Pro","DESKTOP",null,"I3","2 GB","512 GB","500MB",null,"2014-11-29",null),
(163,"Windows 10 Pro","DESKTOP",null,"I5","4 GB","512 GB","500 GB",null,"2014-12-20",null),
(164,"Windows 10 Pro","DESKTOP",null,"I5","4 GB","512 GB","500 GB",null,"2014-12-20",null),
(165,null,"LAPTOP",null,"I7","8 GB",null,"250 GB SSD",null,"2014-11-29",null),
(166,"Windows 10 Pro","DESKTOP",null,"I7","4 GB","1 GB","2 TB",null,"2014-11-29",null),
(167,"Windows 10 Pro","DESKTOP",null,"I7","4 GB","1 GB","2 TB",null,"2014-11-29",null),
(168,"Windows 10 Pro","DESKTOP",null,"I7","4 GB","1 GB","2 TB",null,"2014-11-29",null),
(169,"Windows 10 Pro","DESKTOP",null,"I7","4 GB","1 GB","2 TB",null,"2014-11-29",null),
(170,"Windows 10 Pro","DESKTOP",null,"I7","4 GB","1 GB","2 TB",null,"2014-11-29",null),
(171,"Windows 10 Pro","DESKTOP",null,"I7","4 GB","1 GB","2 TB",null,"2014-11-29",null),
(172,"Windows 10 Pro","DESKTOP",null,"I7","4 GB","1 GB","2 TB",null,"2014-11-29",null),
(173,"Windows 10 Pro","DESKTOP",null,"I7","4 GB","1 GB","2 TB",null,"2014-11-29",null),
(174,"Windows 10 Pro","DESKTOP",null,"I7","4 GB","1 GB","2 TB",null,"2014-11-29",null),
(175,"Windows 10 Pro","DESKTOP",null,"I7","4 GB","1 GB","2 TB",null,"2014-11-29",null),
(176,"Windows 10 Pro","DESKTOP",null,"I7","4 GB","1 GB","2 TB",null,"2014-11-29",null),
(177,"Windows 10 Pro","DESKTOP",null,"I7","4 GB","1 GB","2 TB",null,"2014-11-29",null),
(178,"Windows 10 Pro","DESKTOP",null,"I7","4 GB","1 GB","2 TB",null,"2014-11-29",null),
(179,"Windows 10 Pro","DESKTOP",null,"I7","4 GB","On Board","2 TB",null,"2014-11-29",null),
(180,"Windows 10 Pro","DESKTOP",null,"I7","4 GB","On Board","2 TB",null,"2014-11-29",null),
(181,null,"LAPTOP",null,"I7","8 GB",null,"250 GB SSD",null,"2015-2-12",null),
(182,"Windows 10 Pro","LAPTOP",null,"I3","4 GB","On Board","320 GB",null,"2015-2-12",null),
(183,"Windows 10 Pro","LAPTOP",null,"I3","4 GB","On Board","320 GB",null,"2015-2-12",null),
(184,"Windows 10 Pro","LAPTOP",null,"I3","4 GB","On Board","320 GB",null,"2015-2-12",null),
(185,"Windows 10 Pro","LAPTOP",null,"I3","4 GB","On Board","320 GB",null,"2015-2-12",null),
(186,null,"LAPTOP",null,"I7","8 GB",null,"250 GB SSD",null,"2015-2-12",null),
(187,"Windows 10 Pro","DESKTOP",null,"I3","4 GB","On Board","640GB",null,"2015-5-7",null),
(188,"Windows 10 Pro","DESKTOP",null,"I3","4 GB","On Board","640GB",null,"2015-5-7",null),
(189,"Windows 10 Pro","DESKTOP",null,"I3","4 GB","2 GB","120 GB SSD",null,"2015-6-12",null),
(190,"Windows 10 Pro","DESKTOP",null,"I5","6 GB","2 GB","120 GB SSD + 1 TB",null,"2015-6-12",null),
(191,"Windows 10 Pro","DESKTOP",null,"I3","4 GB","2 GB","120 GB SSD",null,"2015-6-12",null),
(192,"Windows 10 Pro","DESKTOP",null,"I5","6 GB","2 GB","120 GB SSD + 1 TB",null,"2015-6-12",null),
(193,"Windows 10 Pro","DESKTOP",null,"I3","4 GB","2 GB","120 GB SSD",null,"2015-6-12",null),
(194,"Windows 10 Pro","DESKTOP",null,"I5","6 GB","2 GB","120 GB SSD + 1 TB",null,"2015-6-12",null),
(195,"Windows 10 Pro","DESKTOP",null,"I3","4 GB","1 GB","120 GB SSD",null,"2015-6-12",null),
(196,"Windows 10 Pro","DESKTOP",null,"I5","6 GB","1 GB","120 GB SSD + 1 TB",null,"2015-6-12",null),
(197,"Windows 10 Pro","DESKTOP",null,"I3","4 GB","2 GB","120 GB SSD",null,"2015-6-12",null),
(198,"Windows 10 Pro","DESKTOP",null,"I5","6 GB","2 GB","120 GB SSD + 1 TB",null,"2015-6-12",null),
(199,"Mac OSX","LAPTOP",null,"I3","4 GB","On Board","128 GB SSD",null,"2015-10-10",null),
(200,"Mac OSX","LAPTOP",null,"I3","4 GB","On Board","128 GB SSD",null,"2015-10-10",null),
(201,"Windows 10 Pro","DESKTOP",null,"I7","8 GB","2 GB","120 GB SSD + 640GB",null,"2015-12-3",null),
(202,"Windows 10 Pro","DESKTOP",null,"I7","8 GB","2 GB","120 GB SSD + 640GB",null,"2015-12-3",null),
(203,"Windows 10 Pro","DESKTOP",null,"I7","8 GB","2 GB","120 GB SSD + 640GB",null,"2015-12-3",null),
(204,"Windows 10 Pro","DESKTOP",null,"I7","8 GB","2 GB","120 GB SSD + 640GB",null,"2015-12-3",null),
(205,"Windows 10 Pro","DESKTOP",null,"I7","8 GB","2 GB","120 GB SSD + 640GB",null,"2015-12-3",null),
(206,"Windows 10 Pro","DESKTOP",null,"I7","8 GB","2 GB","120 GB SSD + 640GB",null,"2015-12-3",null),
(207,"Windows 10 Pro","DESKTOP",null,"I7","8 GB","2 GB","120 GB SSD + 640GB",null,"2015-12-3",null),
(208,"Windows 10 Pro","DESKTOP",null,"I7","8 GB","2 GB","120 GB SSD + 640GB",null,"2015-12-3",null),
(209,"Windows 10 Pro","DESKTOP",null,"I7","8 GB","2 GB","120 GB SSD + 640GB",null,"2015-12-3",null),
(210,"Windows 10 Pro","DESKTOP",null,"I7","8 GB","2 GB","120 GB SSD + 640GB",null,"2015-12-3",null),
(211,"Windows 10 Pro","DESKTOP",null,"I7","8 GB","2 GB","120 GB SSD + 640GB",null,"2015-12-3",null),
(212,"Windows 10 Pro","DESKTOP",null,"I7","8 GB","2 GB","120 GB SSD + 640GB",null,"2015-12-3",null),
(213,"Windows 10 Pro","LAPTOP",null,"I5","6 GB","On Board","500 GB",null,"2015-12-12",null),
(214,"Windows 10 Pro","LAPTOP",null,"I5","6 GB","On Board","500 GB",null,"2015-12-12",null),
(215,"Windows 10 Pro","LAPTOP",null,"I5","6 GB","On Board","500 GB",null,"2015-12-12",null),
(216,"Windows 10 Pro","DESKTOP",null,"I7","16 GB","4 GB Videocard","120 GB SSD +2TB",null,"2016-5-3",null),
(217,"Windows 10 Pro","DESKTOP",null,"I7","16 GB","2 GB","120 GB SSD +2TB",null,"2016-5-3",null),
(218,"Windows 10 Pro","LAPTOP",null,"I7","8 GB","2 GB on board","250 GB SSD",null,"2016-10-21",null),
(219,"Windows 10 Pro","LAPTOP",null,"I7","8 GB","2 GB on board","250 GB SSD",null,"2016-10-21",null),
(220,"Windows 10 Pro","LAPTOP",null,"I7","8 GB","2 GB on board","250 GB SSD",null,"2016-10-21",null);

DROP TABLE IF EXISTS gebruikers;
CREATE TABLE gebruikers(
    gid INT AUTO_INCREMENT,
    voorletter CHAR(1),
    achternaam VARCHAR(20),
    geslacht VARCHAR(5),
    intern_telefoon_nummer INT,
    afdeling VARCHAR(40),
    postcode CHAR(6),
    email VARCHAR(255),
    PRIMARY KEY (gid)
);

USE project_MA_Twente;
INSERT INTO gebruikers (geslacht, voorletter, achternaam, afdeling, intern_telefoon_nummer, gid, postcode,email)
VALUES
("Dhr","V","Campbell","CAD","254","1","3214BV","vampbell@example.com"),
("Dhr","S","Geerman","CAD","253","2","3215BV","sgeerman@example.com"),
("Mvr","S","Nahuys Van","CAD","252","3","3216BV","Snahayus@example.com"),
("Mvr","F","gcicek","Directie","235","4","3217BV","Fcicek@example.com"),
("Dhr","O","Neville","Directie","236","5","3218BV","Oneville@example.com"),
("Mvr","M","Oldeneel tot Oldenzeel, Van","Directie","234","6","3219BV","Moldeneeltotoldenzeel@example.com"),
("Dhr","Z"," Barney","Engeneering","250","7","3220BV","Zbarney@example.com"),
("Mvr","K","Ali","Engeneering","244","8","3221BV","Kali@example.com"),
("Dhr","Z","Bozkurt","Engeneering","239","9","3222BV","Zbozkurt@example.com"),
("Mvr","A","Conley","Engeneering","245","10","3223BV","Aconley@example.com"),
("Mvr","H","Grotenhuis van Onstein, Van","Engeneering","241","11","3224BV","Hgrotenhuisvanonstein@example.com"),
("Dhr","C","Hall","Engeneering","240","12","3225BV","Chall@example.com"),
("Mvr","M","Hugenpoth, Van","Engeneering","242","13","3226BV","Mhugenpoth@example.com"),
("Dhr","P","Koning","Engeneering","237","14","3227BV","Pkoning@example.com"),
("Dhr","B","Rochussen","Engeneering","247","15","3228BV","Brochussen@example.com"),
("Mvr","K","Schwartzenberg en Hohenlansberg, Thoe","Engeneering","246","16","3229BV","KSchwartzenbergenhohenlansberg@example.com"),
("Mvr","J","Wilder","Engeneering","249","17","3230BV","Jwilder@example.com"),
("Mvr","E","Yallin","Engeneering","248","18","3231BV","Eyalcin@example.com"),
("Dhr","J","Matse","Financiele Administratie","290","19","3232BV","jmatse@example.com"),
("Mvr","N","Kinschot, Van","Financiele Administratie","290","20","3233BV","Nkinschot@example.com"),
("Mvr","K","Nguyen","Financiele Administratie","290","21","3234BV","Knguyen@example.com"),
("Dhr","A","Girard de Mielet van Coehoorn, De","HRM","276","22","3235BV","Agirarddemielet@example.com"),
("Mvr","H","Aktas","ICT","278","23","3236BV","Haktas@example.com"),
("Dhr","S","Harrison","ICT","279","24","3237BV","Sharrison@example.com"),
("Mvr","V","Delen, Van","Onderzoek","263","25","3238BV","Vdelen@example.com"),
("Dhr","T","Galcher","Onderzoek","264","26","3239BV","Tgulcher@example.com"),
("Mvr","L","Leyden, Van","Onderzoek","282","27","3240BV","Lleyden@example.com"),
("Dhr","A","Posson, De","Onderzoek","261","28","3241BV","Aposson@example.com"),
("Mvr","M","Tahiri","Onderzoek","265","29","3242BV","Mtahiri@example.com"),
("Dhr","J","Thompson","Onderzoek","266","30","3243BV","Jthompsons@example.com"),
("Dhr","L","Vos van Steenwijk, De","Onderzoek","281","31","3244BV","Lvosvansteemwijk@example.com"),
("Dhr","E","Westreenen van Tiellandt, Van","Onderzoek","280","32","3245BV","Ewestreenenvantiellandt@example.com"),
("Dhr","F","Erp, Van","Planning","260","33","3246BV","Ferp@example.com"),
("Mvr","J","Flugi van Aspermont","Planning","262","34","3247BV","Jflugiaspermont@example.com"),
("Dhr","V","Harrison","Project planning","259","35","3248BV","Vharrison@example.com"),
("Mvr","K","Malik","Project planning","258","36","3249BV","Kmalik@example.com"),
("Dhr","L","Sasse van Ysselt, Van","Project planning","257","37","3250BV","Lsasseysselt@example.com"),
("Mvr","M","Schinne, Van","Project planning","251","38","3251BV","Mschinne@example.com"),
("Mvr","T","Wolters","Project planning","256","39","3252BV","Twolters@example.com"),
("Dhr","R","Jansz.","Rapportage","277","40","3253BV","Rjansz@example.com"),
("Mvr","D","Bergh, Van Benthem van den","Rapportage","268","41","3254BV","Dbergbenthem@example.com"),
("Dhr","O","Chamberlain","Rapportage","275","42","3255BV","Ochambelein@example.com"),
("Dhr","L","Hesselt van Dinter","Rapportage","267","43","3256BV","Lhesseltvandinter@example.com"),
("Mvr","D","Festetics de Tolna","Secretariaat","243","44","3257BV","Dfesteticsdetolna@example.com"),
("Mvr","S","Sandberg","Secretariaat","238","45","3258BV","Ssandberg@example.com"),
("Mvr","B","Wydenbruck, Von","Secretariaat","255","46","3259BV","Bwydenbruckvon@example.com"),
("Dhr","E","Aslan","Verkoop en Marketing","270","47","3260BV","Easlan@example.com"),
("Mvr","F","Suasso, Lopes","Verkoop en Marketing","270","48","3261BV","Fsuassolopes@example.com"),
("Mvr","J","Thompson","Verkoop en Marketing","270","49","3262BV","Jthompson@example.com");

DROP TABLE IF EXISTS incidenten;
CREATE TABLE incidenten(
    iid INT AUTO_INCREMENT,
    gebruikers_gid INT,
    configuraties_cid INT,
    KorteIncidentBeschrijving VARCHAR(90),
    volledigeIncidentBeschrijving VARCHAR(600),
    betrekkingOpAantalGebruikers INT,
    afhandelTijd DATE,
    verantwoordelijke VARCHAR(40),
    oorzaken VARCHAR(30),
    oplossingen VARCHAR(400),
    terugkoppeling VARCHAR(400),
    status VARCHAR(12),
    PRIMARY KEY (iid)
);

INSERT INTO incidenten (gebruikers_gid, configuraties_cid, korteIncidentBeschrijving, volledigeIncidentBeschrijving, betrekkingOpAantalGebruikers, afhandelTijd, verantwoordelijke, oorzaken, oplossingen, terugkoppeling, status)
VALUES
('S Harrison','NULL','Nieuwe medewerker op projectplanning','Er is een nieuwe medewerkster aangenomen voor projectplanning. Haar naam is Fee Willemse. Ze begint volgende week maandag. Graag account aanmaken met dezelfde rechten als die van haar collega Sigrid van der Wiel.','1','0,25','MaLoZ - ICT Afdeling','Niet van toepassing','Gebruiker is aangemaakt.','Mail met login gegevens verzonden aan hoofd van afdeling.','NULL'),
('L Hesselt van Dinter','NULL','PC loopt soms vast','Detail informatie: Na een half uur werken met de pc wordt het scherm zwart en slaat de pc uit. Na 5 minuten kan de pc weer gebruikt worden, maar werkt dan nog ongeveer een kwartier voordat hij weer uitvalt.','1','3','MaLoZ - ICT Afdeling','CPU-koeling zal vol met stof.','Pc schoongemaakt en getest. Probleem lijkt verholpen.','Pc terug geplaatst en aan gebruiker gemeld.','NULL'),
('M Hugenpoth, Van','NULL','Secretariaat zonder netwerk','Alle pcs van het secretariaat geven aan dat ze niet verbonden zijn met een netwerk.','6','2','MaLoZ - ICT Afdeling','Switch defect','Switch was defect. Deze is vervangen. Nieuwe switch is voorzien van de juiste configuratie-instellingen.','Bij afdeling langs gelopen om te vertellen dat het probleem verholpen is.','NULL'),
('N Kinschot, Van','NULL','Wachtwoord vergeten','Sarisa de Hoogt weet na vakantie haar wachtwoord niet meer.','1','0,1','MaLoZ - ICT Afdeling','Niet van toepassing','Wachtwoord gereset naar standaard waarden. Optie Change password at next logon aagezet.','Gebruiker gebeld met nieuw tijdelijk wachtwoord.','NULL'),
('P Koning','NULL','PC start niet meer op','Bij het opstarten van de pc verschijnt de melding "Boot failure. Reboot en Select proper Boot device or Insert Boot Media in selected Boot device".','1','1,5','MaLoZ - ICT Afdeling','Defecte harddisk','Hardisk vervangen en standaard image terug gezet.','Persoonlijk aan gebuiker doorgegeven dat pc weer werkt.','NULL'),
('L Leyden, Van','NULL','Papier zit vast in printer','Printer geeft melding "Engine Error please contact administrator". Gebruikers printen nu op printer van financi�le administratie.','15','0,25','Leverancier printer','Tandwiel defect','Bij leverancier aangemeld wordt binnen 4 werkdagen vervangen.','Gebruikers gemaild dat de printer binnen 4 werkdagen gerepareerd wordt door de leverancier.','NULL'),
('K Malik','NULL','Java update melding','Op alle kantoorwerkplekken verschijnt dagelijks meerdere malen de melding dat JAVA geupdate moet worden.','40','2','MaLoZ - ICT Afdeling','Oude versie van JAVA was ge�nstalleerd','Via AD nieuwe versie van JAVA uitgerold.','Niet direct teruggemeld aan gebruikers.','NULL'),
('S Nahuys, (Van)','NULL','Netwerk is traag bij financiele administratie','Het benaderen van data vanaf de servers en vanaf het internet is traag. Het gaat wel, maar heel langzaam.','4','3','MaLoZ - ICT Afdeling','Configuratiefout in switch','Alle poorten op 1000 mbps full duplex gezet.','Oplossing aan afdelingshoofd gemeld.','NULL'),
('O Neville','NULL','Geen oplag capaciteit meer op CAD-server','Er kunnen geen bestanden meer opgeslagen worden op de CAD-server. Het openen van bestanden gaat nog wel.','6','3','MaLoZ - ICT Afdeling','Geen capaciteit meer op virtuele disken','Virtuele disken en partities vergroot.','Gemeld aan CAD-tekenaars dat er weer capaciteit is.','NULL'),
('K Nguyen','NULL','Ontslagen medewerker CAD-afdeling','Evert de Vrind, een medewerker van de CAD-afdeling, is op staande voet ontslagen. Zijn account moet per direct afgelosten worden.','1','0,25','MaLoZ - ICT Afdeling','Account disabelen','Account gedisabeld.','Aan HRM doorgegeven dat account uitstaat.','NULL'),
('M Oldeneel tot Oldenzeel, Van','NULL','Verhuizen werkplek','Werkplek van secretariaat moet omgezet worden naar de afdeling HRM.','1','2','MaLoZ - ICT Afdeling','Niet van toepassing','Desktop verhuisd, nieuwe patch gemaakt en oude verwijderd. Patch documentatie is bijgewerkt.','Gebruiker ging direct op nieuwe plaats aan het werk.','NULL'),
('A Posson, De','NULL','Voettekst op spreadsheet PDF','Gebruiker wilt PDF maken met spreadsheet. In die voettekst moet datum en versie vermeld worden.','1','1','MaLoZ - ICT Afdeling','Voetteksten in Excel','Gebruiker uitgelegd hoe voetteksten in Excel werken. En verteld van de werking van CutePDF. Enkele malen het hele proces gezamenlijk doorlopen. Gebruiker vindt dit lastig.','Niet van toepassing','NULL'),
('B Rochussen','NULL','Netwerk plat. ','Netwerk lijkt in zijn geheel niet meer te werken. ','80','2,5','MaLoZ - ICT Afdeling','Patchfout','Patchfout heeft netwerkloop veroorzaakt.','Gemeld aan secretariaat. Die verzorgen communicatie naar rest van het bedrijf.','NULL'),
('S Sandberg','NULL','Standaard printer','In verband met defecte printer wilt gebruiker dat prints automatisch uit de printer van HRM komen.','1','0,25','MaLoZ - ICT Afdeling','Andere standaard printer','Remote HRM printer ingesteld als standaard.','Niet van toepassing','NULL'),
('L Sasse van Ysselt, Van','NULL','Administratie pakket niet toegangelijk','Gebruiker kan niet inloggen op administratiepakket.','1','0,25','MaLoZ - ICT Afdeling','Gebruiker aanmaken in administratiepakket','Gebuiker aangemaakt in administratiepakket. Gebruiker had nog geen account.','Aan hoofd van de afdeling gemeld dat de gebruiker kan inloggen.','NULL'),
('M Schinne, Van','NULL','Vreemde paginas op internet','Bij opstarten internetbrowser worden advertenties getoond. Bij weg klikken komen er steeds meer advertenties.','1','1','MaLoZ - ICT Afdeling','Malware verwijderd.','Malware van laptop verwijderd.','Gebruiker gemeld en komt laptop weer ophalen.','NULL'),
('K Schwartzenberg en Hohenlansberg, Thoe','NULL','Lokaal wachtwoord kwijt','Is het wachtwoord van priv�laptop vergeten. Graag wachtwoord verwijderen of instellen op ander wachtwoord.','1','1,5','MaLoZ - ICT Afdeling','Wachtwoord terug gezocht.','Met behulp van tool Windows wachtwoord achterhaald.','Wachtwoord telefonisch aan gebruiker doorgegeven.','NULL'),
('M.   Barney','NULL','Wachtwoord vergeten','Mark Barney weet na zijn vakantie zijn wachtwoord niet meer.','1','0,1','MaTW - ICT Afdeling','Niet van toepassing','Wachtwoord gereset naar standaard waarden. Optie Change password at next logon aagezet.','Gebruiker gebeld met nieuw tijdelijk wachtwoord.','NULL'),
('R.   Jansz.','NULL','Bestand met planning van project is weg.','Bestand staat niet meer in de map van het project. Bestand is vorige week dinsdag voor het laatst aangevuld en opgeslagen.','2','1','MaTW - ICT Afdeling','Bestand gewist','Bestand teruggehaald van restore.','Gemeld dat bestand terug staat.','NULL'),
('J.   Matse','NULL','E-mail niet beschikbaar','E-mailomgeving is niet te benaderen door kantoor en buitendienst medewerkers.','80','2','Hosting provider','DNS-configuratie fout Hosting provider','Provider gecontact, deze hebben de fout in DNS-server opgelost. Aanpassing duurt 4 uur voordat deze overal doorwerkt.','Alle gebruikers een e-mail gestuurd dat het probleem opgelost is.','NULL'),
('H.  Akta?','NULL','Secties in Word','Gebruiker wil een pagina in een Word document landscape afdrukken. Paginas voor en na deze pagina dienen portrait te blijven.','1','0,5','MaTW - ICT Afdeling','Secties gebruiken','Met gebruiker meegekeken, de werking van secties uitgelegd en samen ingesteld voor het document.','Niet van toepassing.','NULL'),
('K.  Ali','NULL','Piepjes bij aanzetten laptop','Als laptop opstart alleen drie piepjes te horen. Laptop doet verder niets.','1','1,5','MaTW - ICT Afdeling','Geheugen vervangen','Geheugen blijkt defect. Geheugen vervangen. Geheugen wordt RMA gestuurd.','Gebruiker heeft laptop direct meegenomen.','NULL'),
('E.  Aslan','NULL','E-mail op priv�tablet','Gebruiker wilt zakeljke e-mail op priv�tablet','1','0,25','MaTW - ICT Afdeling','Standaard instellingen','Telefonisch samen met de gebruiker tablet ingesteld.','Niet van toepassing.','NULL'),
('D. van den Bergh','NULL','Breuk in laptopscherm','Laptop is gevallen. Er zit nu een breuk in scherm.','1','1,5','MaTW - ICT Afdeling','Tijdelijk andere laptop','Data overgezet naar tijdelijke laptop. Deze laptop wordt opgestuurd naar leverancier voor reparatie.','Aan gebruiker gemeld dat nieuwe laptop opgehaald kan worden.','NULL'),
('Z.  Bozkurt','NULL','Wachtwoord omzetten','Ik wil e-mailinstellingen van een extern e-mailadres op mijn tablet instellen, maar ik weet het wachtwoord niet meer. Account met wachtwoord zit nog wel op laptop van de zaak.','1','1','MaTW - ICT Afdeling','Wachtwoord terug gezocht.','Met behulp van wachtwoord tool wachtwoord in Outlook zichtbaar gemaakt.','Wachtwoord telefonisch aan gebruiker doorgegeven.','NULL'),
('V.  Campbell','NULL','Buitendienstmedewerkers geen toegang tot urenadministratie','Alle buitendienstmedewerkers kunnen na de update niet meer inloggen op de urenadministratie.','1','3','MaTW - ICT Afdeling','IP-routing niet goed','Route naar VPN server toegevoegd aan routing tabel van server.','Alle buitendienstmedewerkers gemaild.','NULL'),
('O.  Chamberlain','NULL','Hoe stel ik de afwezigheidsassistent in?','Gebruiker wil tijdens vakantie afwezigheidsassistent aanzetten.','1','0,25','MaTW - ICT Afdeling','Bedrijfsbeleid uitgelegd','Uitgelegd aan gebruiker dat deze optie niet aanstaat in het systeem. Bedrijfsbeleid is om collegas tijdens de vakantie toegang te geven tot je mailbox zodat deze de mail kunnen bijhouden.','Niet van toepassing.','NULL'),
('F.  �i�ek','NULL','per ongeluk een bestand verwijderd','Op de harddisk van mijn laptop heb ik per ongeluk een bestand verwijderd. Dit is een rapportage die ik nog niet had opgeslagen op de server. Hier zit drie weken werk in. Het is belangrijk dat deze terug komt.','1','3','MaTW - ICT Afdeling','Bestand gerecoverd','Met tool bestand teruggehaald.','Bestand op server gezet en gebruiker gemaild.','NULL'),
('A.  Conley','NULL','Pc reageert heel traag ook na herstarten','Pc is traag. Ook nadat door ICT-afdeling een nieuwe image ge�nstalleerd is.','1','2','MaTW - ICT Afdeling','BIOS-instellingen goed zetten','Na draaien van performace tool bleken BIOS-instellingen geheugen niet goed te staan.','Gebruiker laptop terug gegeven.','NULL'),
('V.  Van Delen','NULL','Lokaal wachtwoord kwijt','Gebruiker is het wachtwoord van priv�laptop vergeten. Graag wachtwoord verwijderen of instellen op ander wachtwoord.','1','1,5','MaTW - ICT Afdeling','Wachtwoord teruggezocht','Met behulp van tool Windows wachtwoord achterhaald.','Wachtwoord telefonisch aan gebruiker doorgegeven.','NULL'),
('F.  Van Erp','NULL','Vreemde paginas op internet','Bij opstarten internetbrowser worden advertenties getoond. Bij wegklikken komen er steeds meer advertenties.','1','1','MaTW - ICT Afdeling','Malware verwijderd','Malware van laptop verwijderd.','Gebruiker gemeld en komt laptop weer ophalen.','NULL'),
('D.  Festetics de Tolna','NULL','Iemand probeert in te loggen op laptop','Ik heb het idee dat iemand op afstand probeert in te loggen op mijn laptop. Is het mogelijk om hier iets van te achterhalen?','1','0,5','MaTW - ICT Afdeling','Logfiles bekeken','Remote logs bekeken en er probeert inderdaad iemand via remote desktop in te loggen. Remote desktop op laptop is nu uitgezet.','Telefonisch aan gebruiker doorgegeven.','NULL'),
('J.  Flugi van Aspermont','NULL','Geen VPN-toegang','Buitendienstmedewerkers hebben geen toegang meer tot het netwerk.','40','4','MaTW - ICT Afdeling','Interface in router defect','WAN-interface van router die werkt als VPN-server defect. Reservekaart geplaatst, opnieuw geconfigureerd en getest.','Alle buitendienstmedewerkers gemaild.','NULL');
