USE project_Ma_Twente;
DROP TABLE IF EXISTS gebruikers;
CREATE TABLE gebruikers(
    gid INT AUTO_INCREMENT,
    configuraties_cid INT,
    voornaam VARCHAR(20),
    achternaam VARCHAR(20),
    geslacht VARCHAR(5),
    intern_telefoon_nummer INT,
    afdeling VARCHAR(40),
    postcode CHAR(6),
    email VARCHAR(255),
    PRIMARY KEY (gid)
);

INSERT INTO gebruikers (geslacht, voorletter, achternaam, afdeling, intern_telefoon_nummer, gid, postcode,email)
VALUES
("Dhr","V","Campbell","CAD","254","1","3214BV","vampbell@example.com"),
("Dhr","S","Geerman","CAD","253","2","3215BV","sgeerman@example.com"),
("Mvr","S","Nahuys Van","CAD","252","3","3216BV","Snahayus@example.com"),
("Mvr","F","gcicek","Directie","235","4","3217BV","Fcicek@example.com"),
("Dhr","O","Neville","Directie","236","5","3218BV","Oneville@example.com"),
("Mvr","M","Oldeneel tot Oldenzeel, Van","Directie","234","6","3219BV","Moldeneeltotoldenzeel@example.com"),
("Dhr","Z"," Barney","Engeneering","250","7","3220BV","Zbarney@example.com"),
("Mvr","K","Ali","Engeneering","244","8","3221BV","Kali@example.com"),
("Dhr","Z","Bozkurt","Engeneering","239","9","3222BV","Zbozkurt@example.com"),
("Mvr","A","Conley","Engeneering","245","10","3223BV","Aconley@example.com"),
("Mvr","H","Grotenhuis van Onstein, Van","Engeneering","241","11","3224BV","Hgrotenhuisvanonstein@example.com"),
("Dhr","C","Hall","Engeneering","240","12","3225BV","Chall@example.com"),
("Mvr","M","Hugenpoth, Van","Engeneering","242","13","3226BV","Mhugenpoth@example.com"),
("Dhr","P","Koning","Engeneering","237","14","3227BV","Pkoning@example.com"),
("Dhr","B","Rochussen","Engeneering","247","15","3228BV","Brochussen@example.com"),
("Mvr","K","Schwartzenberg en Hohenlansberg, Thoe","Engeneering","246","16","3229BV","KSchwartzenbergenhohenlansberg@example.com"),
("Mvr","J","Wilder","Engeneering","249","17","3230BV","Jwilder@example.com"),
("Mvr","E","Yallin","Engeneering","248","18","3231BV","Eyalcin@example.com"),
("Dhr","J","Matse","Financiele Administratie","290","19","3232BV","jmatse@example.com"),
("Mvr","N","Kinschot, Van","Financiele Administratie","290","20","3233BV","Nkinschot@example.com"),
("Mvr","K","Nguyen","Financiele Administratie","290","21","3234BV","Knguyen@example.com"),
("Dhr","A","Girard de Mielet van Coehoorn, De","HRM","276","22","3235BV","Agirarddemielet@example.com"),
("Mvr","H","Aktas","ICT","278","23","3236BV","Haktas@example.com"),
("Dhr","S","Harrison","ICT","279","24","3237BV","Sharrison@example.com"),
("Mvr","V","Delen, Van","Onderzoek","263","25","3238BV","Vdelen@example.com"),
("Dhr","T","Galcher","Onderzoek","264","26","3239BV","Tgulcher@example.com"),
("Mvr","L","Leyden, Van","Onderzoek","282","27","3240BV","Lleyden@example.com"),
("Dhr","A","Posson, De","Onderzoek","261","28","3241BV","Aposson@example.com"),
("Mvr","M","Tahiri","Onderzoek","265","29","3242BV","Mtahiri@example.com"),
("Dhr","J","Thompson","Onderzoek","266","30","3243BV","Jthompsons@example.com"),
("Dhr","L","Vos van Steenwijk, De","Onderzoek","281","31","3244BV","Lvosvansteemwijk@example.com"),
("Dhr","E","Westreenen van Tiellandt, Van","Onderzoek","280","32","3245BV","Ewestreenenvantiellandt@example.com"),
("Dhr","F","Erp, Van","Planning","260","33","3246BV","Ferp@example.com"),
("Mvr","J","Flugi van Aspermont","Planning","262","34","3247BV","Jflugiaspermont@example.com"),
("Dhr","V","Harrison","Project planning","259","35","3248BV","Vharrison@example.com"),
("Mvr","K","Malik","Project planning","258","36","3249BV","Kmalik@example.com"),
("Dhr","L","Sasse van Ysselt, Van","Project planning","257","37","3250BV","Lsasseysselt@example.com"),
("Mvr","M","Schinne, Van","Project planning","251","38","3251BV","Mschinne@example.com"),
("Mvr","T","Wolters","Project planning","256","39","3252BV","Twolters@example.com"),
("Dhr","R","Jansz.","Rapportage","277","40","3253BV","Rjansz@example.com"),
("Mvr","D","Bergh, Van Benthem van den","Rapportage","268","41","3254BV","Dbergbenthem@example.com"),
("Dhr","O","Chamberlain","Rapportage","275","42","3255BV","Ochambelein@example.com"),
("Dhr","L","Hesselt van Dinter","Rapportage","267","43","3256BV","Lhesseltvandinter@example.com"),
("Mvr","D","Festetics de Tolna","Secretariaat","243","44","3257BV","Dfesteticsdetolna@example.com"),
("Mvr","S","Sandberg","Secretariaat","238","45","3258BV","Ssandberg@example.com"),
("Mvr","B","Wydenbruck, Von","Secretariaat","255","46","3259BV","Bwydenbruckvon@example.com"),
("Dhr","E","Aslan","Verkoop en Marketing","270","47","3260BV","Easlan@example.com"),
("Mvr","F","Suasso, Lopes","Verkoop en Marketing","270","48","3261BV","Fsuassolopes@example.com"),
("Mvr","J","Thompson","Verkoop en Marketing","270","49","3262BV","Jthompson@example.com");
